version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17

    working_directory: /home/circleci/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test
      - run: yarn build
      - run: cat coverage/lcov.info | npx coveralls
      - persist_to_workspace:
          root: .
          paths:
            - lib
  publish:
    docker:
      - image: circleci/node:10.17
    working_directory: /home/circleci/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - attach_workspace:
          at: /home/circleci/repo
      - run: npm publish

workflows:
  version: 2
  test-build-publish:
    jobs:
      - build:
          filters:
            branches: { only: /.*/ }
            tags: { only: /.*/ }
      - publish:
          filters:
            branches: { ignore: /.*/ }
            tags: { only: /.*/ }
          requires:
            - build
