
version: 2        
jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: echo "hello world"
      - run:
          environment:
            TTT: $TEST
          command: echo $TTT


workflows:
  version: 2
  workflow:
    jobs:
      - build
