version: 2


- &fastlane
    run:
        name: Fastlane
        no_output_timeout: 60m
        command: bundle exec fastlane ${LANE:-$CIRCLE_JOB}   
        
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run: echo "hello world"


workflows:
  version: 2
  workflow:
    jobs:
    - build
