
version: 2        
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo $PWD


workflows:
  version: 2
  workflow:
    jobs:
      - build
